root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./target/debug/rust-web"
  cmd = "./build.sh"
  delay = 1000
  exclude_dir = ["target", "public", "static", "tmp", "vendor", "testdata", "assets/node_modules", "assets/css-toolchain/dist", "assets/css-toolchain/node_modules"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["rs", "html", "css", "js"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false