[package]
name = "rust-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-settings = "0.6.0"
env_logger = "0.9.0"
askama = "0.11.1"
askama_actix = "0.13.0"
bytes = "1.2.0"
